//go:build jelee_fixture_tools

package main

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/MoYuanCN/Jelee/internal/adapter/probe"
	"github.com/MoYuanCN/Jelee/internal/domain"
	"github.com/MoYuanCN/Jelee/internal/platform/process"
	"github.com/MoYuanCN/Jelee/tools"
)

// This opt-in, developer-tag test is the only registration below. Inputs are
// generated by this test. It is absent from production builds and does not
// establish a sandbox for arbitrary media supplied by users.
func TestParseActualPinnedFFprobeFixtures(t *testing.T) {
	project := fixtureProject(t)
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()
	output, err := generate(ctx, project)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := os.RemoveAll(output); err != nil {
			t.Error("owned fixture cleanup failed")
		}
	})
	spec, err := tools.FFprobeSpec(runtime.GOOS + "-" + runtime.GOARCH)
	if err != nil {
		t.Fatal(err)
	}
	root, err := os.OpenRoot(project)
	if err != nil {
		t.Fatal("project root unavailable")
	}
	defer root.Close()
	if err := verifyFile(root, spec.ExecutablePath, spec.SHA256); err != nil {
		t.Fatal("required embedded ffprobe identity did not match")
	}
	for _, license := range spec.Licenses {
		if err := verifyFile(root, license.Path, license.SHA256); err != nil {
			t.Fatal("required ffprobe license did not match")
		}
	}
	tempParent := filepath.Join(project, ".testdata")
	if err := os.Mkdir(tempParent, 0700); err != nil && !errors.Is(err, os.ErrExist) {
		t.Fatal("test process parent unavailable")
	}
	info, err := os.Lstat(tempParent)
	if err != nil || info.Mode().Type() != os.ModeDir {
		t.Fatal("test process parent must be a regular directory")
	}
	temp, err := os.MkdirTemp(tempParent, "parser-fixture-")
	if err != nil {
		t.Fatal("test process directory unavailable")
	}
	t.Cleanup(func() {
		if err := os.RemoveAll(temp); err != nil {
			t.Error("owned process directory cleanup failed")
		}
	})
	runner, err := process.New(process.Config{MaxConcurrent: 1, Timeout: 15 * time.Second, MaxStdoutBytes: probe.MaxJSONBytes, MaxStderrBytes: 64 << 10, TempRoot: temp}, []process.Tool{{ID: "ffprobe", Path: filepath.Join(project, filepath.FromSlash(spec.ExecutablePath)), Operations: map[string][]string{"self_generated_fixture": probe.FFprobeFDArguments(), "version": {"-version"}}}})
	if err != nil {
		t.Fatal(err)
	}
	version, err := runner.Run(ctx, process.Request{Tool: "ffprobe", Operation: "version"})
	if err != nil || !strings.HasPrefix(string(version.Stdout), "ffprobe version "+spec.VendorVersion+" ") {
		t.Fatal("required ffprobe version did not match")
	}
	for _, test := range []struct {
		name                                               string
		width, height, streams, audio, subtitles, chapters int
		formats                                            []string
	}{
		{"video-180p.mp4", 320, 180, 2, 1, 0, 0, []string{"mov", "mp4", "m4a", "3gp", "3g2", "mj2"}},
		{"video-360p.mp4", 640, 360, 2, 1, 0, 0, []string{"mov", "mp4", "m4a", "3gp", "3g2", "mj2"}},
		{"multi.mkv", 320, 180, 5, 2, 2, 2, []string{"matroska", "webm"}},
	} {
		t.Run(test.name, func(t *testing.T) {
			path := filepath.Join(output, test.name)
			before, err := os.ReadFile(path)
			if err != nil {
				t.Fatal("fixture unavailable")
			}
			beforeHash := sha256.Sum256(before)
			input, err := probe.Open(ctx, probe.Source{RootPath: output, RelativePath: test.name})
			if err != nil {
				t.Fatal(err)
			}
			result, runErr := runner.Run(ctx, process.Request{Tool: "ffprobe", Operation: "self_generated_fixture", Stdin: input.Stdin()})
			closeErr := input.Close()
			if runErr != nil {
				t.Fatal(runErr)
			}
			if closeErr != nil {
				t.Fatal(closeErr)
			}
			metadata, err := probe.ParseJSON(result.Stdout)
			if err != nil {
				t.Fatal(err)
			}
			if len(metadata.Streams) != test.streams || len(metadata.Chapters) != test.chapters {
				t.Fatalf("stream/chapter counts: %d/%d", len(metadata.Streams), len(metadata.Chapters))
			}
			if metadata.Format.SizeBytes == nil || *metadata.Format.SizeBytes != int64(len(before)) {
				t.Fatal("format size differs from the read-only source")
			}
			// AAC encoder priming can extend the Matroska duration slightly. The
			// generated source is one second; this bound accommodates that padding.
			if metadata.Format.DurationMicros == nil || *metadata.Format.DurationMicros < 1000000 || *metadata.Format.DurationMicros > 1100000 {
				t.Fatal("one-second fixture duration was not normalized")
			}
			if metadata.Format.BitRate == nil || *metadata.Format.BitRate <= 0 {
				t.Fatal("format bitrate missing")
			}
			if strings.Join(metadata.Format.Names, ",") != strings.Join(test.formats, ",") {
				t.Fatalf("format names: %v", metadata.Format.Names)
			}
			videoCount, audioCount, subtitleCount := 0, 0, 0
			languages := make(map[string]bool)
			for _, stream := range metadata.Streams {
				switch stream.Kind {
				case "video":
					videoCount++
					if stream.Codec == nil || *stream.Codec != "h264" || stream.Video == nil || stream.Video.Width == nil || stream.Video.Height == nil || *stream.Video.Width != int64(test.width) || *stream.Video.Height != int64(test.height) {
						t.Fatal("video codec or dimensions mismatch")
					}
					if stream.Video.FrameRate == nil || *stream.Video.FrameRate != (domain.MediaRational{Numerator: 24, Denominator: 1}) || stream.Video.AverageFrameRate == nil || *stream.Video.AverageFrameRate != (domain.MediaRational{Numerator: 24, Denominator: 1}) {
						t.Fatal("video frame rate mismatch")
					}
					if stream.Profile == nil || *stream.Profile != "Constrained Baseline" {
						t.Fatal("video profile mismatch")
					}
					if stream.Video.DolbyVision != nil || stream.Video.HDR10Plus != nil || stream.Video.MasteringDisplay != nil || stream.Video.ContentLight != nil {
						t.Fatal("ordinary fixture gained unobserved HDR metadata")
					}
				case "audio":
					audioCount++
					if stream.Codec == nil || *stream.Codec != "aac" || stream.Audio == nil || stream.Audio.Channels == nil || *stream.Audio.Channels != 1 || stream.Audio.SampleRate == nil || *stream.Audio.SampleRate != 48000 || stream.Audio.ChannelLayout == nil || *stream.Audio.ChannelLayout != "mono" || stream.Audio.Atmos != nil {
						t.Fatal("audio metadata mismatch")
					}
				case "subtitle":
					subtitleCount++
					if stream.Codec == nil || *stream.Codec != "subrip" || stream.Language == nil || stream.Default == nil || stream.Forced == nil || *stream.Forced {
						t.Fatal("subtitle metadata mismatch")
					}
					languages[*stream.Language] = true
				default:
					t.Fatalf("unexpected stream kind %q", stream.Kind)
				}
			}
			if videoCount != 1 || audioCount != test.audio || subtitleCount != test.subtitles {
				t.Fatal("typed stream counts mismatch")
			}
			if test.subtitles > 0 && (!languages["eng"] || !languages["zho"]) {
				t.Fatal("subtitle languages mismatch")
			}
			for index, chapter := range metadata.Chapters {
				if chapter.StartMicros == nil || chapter.EndMicros == nil || *chapter.StartMicros != int64(index)*500000 || *chapter.EndMicros != int64(index+1)*500000 {
					t.Fatal("chapter time normalization mismatch")
				}
			}
			encoded, err := json.Marshal(metadata)
			if err != nil {
				t.Fatal(err)
			}
			for _, private := range []string{"fd:", "Jelee synthetic test", "Part one", "Part two", `"filename"`, `"title"`, output} {
				if strings.Contains(string(encoded), private) {
					t.Fatal("normalized metadata retained source/track data")
				}
			}
			after, err := os.ReadFile(path)
			if err != nil || sha256.Sum256(after) != beforeHash {
				t.Fatal("read-only probe changed original fixture")
			}
			t.Logf("actual %s: h264 %dx%d; audio=%d subtitles=%d chapters=%d; size=%d durationMicros=%d; sourceSHA256=%s unchanged", test.name, test.width, test.height, audioCount, subtitleCount, len(metadata.Chapters), *metadata.Format.SizeBytes, *metadata.Format.DurationMicros, hex.EncodeToString(beforeHash[:]))
		})
	}
	t.Run("corrupt_refused", func(t *testing.T) {
		path := filepath.Join(output, "corrupt.mkv")
		before, err := os.ReadFile(path)
		if err != nil {
			t.Fatal("corrupt fixture unavailable")
		}
		input, err := probe.Open(ctx, probe.Source{RootPath: output, RelativePath: "corrupt.mkv"})
		if err != nil {
			t.Fatal(err)
		}
		result, err := runner.Run(ctx, process.Request{Tool: "ffprobe", Operation: "self_generated_fixture", Stdin: input.Stdin()})
		input.Close()
		if !errors.Is(err, process.ErrExit) || len(result.Stdout) != 0 {
			t.Fatal("corrupt probe did not fail safely")
		}
		if _, err := probe.ParseJSON(result.Stdout); !errors.Is(err, probe.ErrMetadataInvalid) {
			t.Fatal("empty failed probe output became valid metadata")
		}
		after, err := os.ReadFile(path)
		if err != nil || sha256.Sum256(before) != sha256.Sum256(after) {
			t.Fatal("corrupt source changed")
		}
	})
	t.Logf("Pinned ffprobe %s (%s); this test covers self-generated h264/aac/subrip media only, not HDR/DV/Atmos or arbitrary-media sandboxing.", spec.VendorVersion, spec.Platform)
}
