//go:build jelee_fixture_tools

package main

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"testing"
	"time"

	"github.com/MoYuanCN/Jelee/internal/adapter/probe"
	"github.com/MoYuanCN/Jelee/internal/platform/process"
)

// This developer test probes only the original media generated by this test.
// It does not register an operation on the production service.
func TestRealFixtureProbeMetadataAndSourcePreservation(t *testing.T) {
	project := fixtureProject(t)
	spec, _, err := loadTool(project)
	if err != nil {
		t.Fatal(err)
	}
	root, err := os.OpenRoot(project)
	if err != nil {
		t.Fatal(err)
	}
	defer root.Close()
	tool := spec.Executables["ffprobe"]
	rel := ".tools/" + spec.InstallPath + "/" + tool.Path
	if err := verifyFile(root, rel, tool.SHA256); err != nil {
		t.Fatal(err)
	}
	output, err := generate(context.Background(), project)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { os.RemoveAll(output) })
	raw, err := os.ReadFile(filepath.Join(output, "fixtures.json"))
	if err != nil {
		t.Fatal(err)
	}
	var manifest fixtureManifest
	if err := json.Unmarshal(raw, &manifest); err != nil {
		t.Fatal(err)
	}
	temp := filepath.Join(output, "probe-process")
	if err := os.Mkdir(temp, 0700); err != nil {
		t.Fatal(err)
	}
	runner, err := process.New(process.Config{MaxConcurrent: 1, Timeout: 10 * time.Second, MaxStdoutBytes: 4 << 20, MaxStderrBytes: 64 << 10, TempRoot: temp}, []process.Tool{{ID: "ffprobe", Path: filepath.Join(project, filepath.FromSlash(rel)), Operations: map[string][]string{"metadata": probe.FFprobeFDArguments()}}})
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range manifest.Files {
		if filepath.Ext(entry.Name) != ".mp4" && filepath.Ext(entry.Name) != ".mkv" {
			continue
		}
		t.Run(entry.Name, func(t *testing.T) {
			input, err := probe.Open(context.Background(), probe.Source{RootPath: output, RelativePath: entry.Name})
			if err != nil {
				t.Fatal(err)
			}
			result, runErr := runner.Run(context.Background(), process.Request{Tool: "ffprobe", Operation: "metadata", Stdin: input.Stdin()})
			input.Close()
			if entry.Expected.Invalid {
				if runErr == nil {
					t.Fatal("corrupt fixture probed successfully")
				}
				if len(result.Stdout) != 0 {
					t.Fatal("raw failure output retained")
				}
			} else {
				if runErr != nil {
					t.Fatalf("real pinned fd probe failed: %v", runErr)
				}
				var metadata struct {
					Streams []struct {
						CodecType string `json:"codec_type"`
						CodecName string `json:"codec_name"`
						Width     int    `json:"width"`
						Height    int    `json:"height"`
						// Disposition marks the embedded cover of the cover fixtures.
						Disposition struct {
							AttachedPic int `json:"attached_pic"`
						} `json:"disposition"`
					} `json:"streams"`
					Chapters []json.RawMessage `json:"chapters"`
					Format   struct {
						Duration string `json:"duration"`
						Size     string `json:"size"`
					} `json:"format"`
				}
				if err := json.Unmarshal(result.Stdout, &metadata); err != nil {
					t.Fatal("probe returned invalid JSON")
				}
				var video, audio, subtitles, attachments, covers int
				for _, stream := range metadata.Streams {
					switch stream.CodecType {
					case "video":
						video++
						if stream.Disposition.AttachedPic == 1 {
							covers++
							if stream.CodecName != "mjpeg" && stream.CodecName != "png" || stream.Width != 16 || stream.Height != 16 {
								t.Fatal("wrong embedded cover metadata")
							}
							continue
						}
						if stream.CodecName != "h264" || stream.Width != entry.Expected.Width || stream.Height != entry.Expected.Height {
							t.Fatal("wrong video metadata")
						}
					case "audio":
						audio++
						if stream.CodecName != "aac" {
							t.Fatal("wrong audio codec")
						}
					case "subtitle":
						subtitles++
						if stream.CodecName != "subrip" && stream.CodecName != "ass" {
							t.Fatal("wrong subtitle codec")
						}
					case "attachment":
						attachments++
					}
				}
				if (covers == 1) != (entry.Expected.CoverSHA256 != "") || covers > 1 {
					t.Fatal("embedded cover expectation differs")
				}
				if video != entry.Expected.Video || audio != entry.Expected.Audio || subtitles != entry.Expected.Subtitles || attachments != entry.Expected.Attachments || len(metadata.Chapters) != entry.Expected.Chapters {
					t.Fatal("wrong stream/chapter counts")
				}
				duration, err := strconv.ParseFloat(metadata.Format.Duration, 64)
				if err != nil || duration < 0.9 || duration > 1.2 {
					t.Fatal("wrong duration")
				}
				size, err := strconv.ParseInt(metadata.Format.Size, 10, 64)
				if err != nil || size != entry.Bytes {
					t.Fatal("wrong file size")
				}
			}
			data, err := os.ReadFile(filepath.Join(output, entry.Name))
			if err != nil {
				t.Fatal(err)
			}
			hash := sha256.Sum256(data)
			if hex.EncodeToString(hash[:]) != entry.SHA256 {
				t.Fatal("original media changed")
			}
		})
	}
}
