package postgres

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/MoYuanCN/Jelee/internal/adapter/legacydb"
	"github.com/MoYuanCN/Jelee/internal/adapter/legacydb/legacydbtest"
	"github.com/MoYuanCN/Jelee/internal/domain"
)

// Legacy import integration tests (G04.6). Every source database is
// generated by legacydbtest; none holds real user data.

const (
	lgAlice     = "a1000000-0000-4000-8000-000000000001"
	lgBob       = "a1000000-0000-4000-8000-000000000002"
	lgCarol     = "a1000000-0000-4000-8000-000000000003"
	lgUnicode   = "a1000000-0000-4000-8000-000000000004"
	lgGone      = "a1000000-0000-4000-8000-0000000000ff" // deleted upstream: user data only
	lgMovies    = "b2000000-0000-4000-8000-000000000001"
	lgShows     = "b2000000-0000-4000-8000-000000000002"
	lgMusic     = "b2000000-0000-4000-8000-000000000003"
	lgLiveTV    = "b2000000-0000-4000-8000-000000000004"
	lgMovie1    = "c3000000-0000-4000-8000-000000000001"
	lgMovie2    = "c3000000-0000-4000-8000-000000000002"
	lgMovie2b   = "c3000000-0000-4000-8000-000000000003" // second version of movie 2
	lgMissing   = "c3000000-0000-4000-8000-000000000004" // file deleted from disk
	lgOutside   = "c3000000-0000-4000-8000-000000000005" // under no library root
	lgSeries    = "c3000000-0000-4000-8000-000000000006"
	lgSeason    = "c3000000-0000-4000-8000-000000000007"
	lgEpisode   = "c3000000-0000-4000-8000-000000000008"
	lgVirtual   = "c3000000-0000-4000-8000-000000000009"
	lgExtra     = "c3000000-0000-4000-8000-00000000000a"
	lgAudio     = "c3000000-0000-4000-8000-00000000000b"
	lgBook      = "c3000000-0000-4000-8000-00000000000c"
	lgChannel   = "c3000000-0000-4000-8000-00000000000d"
	lgTrailer   = "c3000000-0000-4000-8000-00000000000e"
	lgFolder    = "c3000000-0000-4000-8000-00000000000f"
	lgVanished  = "c3000000-0000-4000-8000-0000000000ff" // user data of an item that is gone
	lgPlaceItem = domain.LegacyPlaceholderItemID
)

type legacyScenario struct {
	ctx    context.Context
	s      *Store
	source string // upstream database path
	media  string // target media directory
	rules  []domain.LegacyPathRule
}

func legacyFixtureSpec() legacydbtest.Spec {
	rating := 13
	bitrate := int64(8_000_000)
	return legacydbtest.Spec{
		Users: []legacydbtest.User{
			{ID: lgAlice, Name: "Alice", Password: "$PBKDF2-SHA512$iterations=210000$00$00", Permissions: map[int]bool{0: true, 16: true, 11: true, 4: true}},
			{ID: lgBob, Name: "bob", MaxRating: &rating, Bitrate: &bitrate, MaxSessions: 2,
				Permissions: map[int]bool{16: false, 6: true, 7: true}, Preferences: map[int]string{5: strings.ToLower(lgMovies) + "," + lgMusic, 0: "Horror, gore", 10: "Movie", 11: "x"}},
			{ID: lgCarol, Name: "Carol", Permissions: map[int]bool{16: true}},
			{ID: lgUnicode, Name: "測試ユーザー", Permissions: map[int]bool{1: true, 2: true, 16: true}},
		},
		Libraries: []legacydbtest.Library{
			{ID: lgMovies, Name: "電影 Movies", CollectionType: "movies", Locations: []string{"/legacy/媒体/电影", "/legacy/媒体/电影/"}},
			{ID: lgShows, Name: "Shows", CollectionType: "tvshows", Locations: []string{"/legacy/shows"}},
			{ID: lgMusic, Name: "Music", CollectionType: "music", Locations: []string{"/legacy/music"}},
			{ID: lgLiveTV, Name: "Live", CollectionType: "livetv"},
		},
		Items: []legacydbtest.Item{
			{ID: lgMovie1, Type: legacydbtest.TypeMovie, Path: "/legacy/媒体/电影/千と千尋 (2001)/千と千尋.mkv"},
			{ID: lgMovie2, Type: legacydbtest.TypeMovie, Path: "/legacy/媒体/电影/Heat (1995)/Heat - 1080p.mkv"},
			{ID: lgMovie2b, Type: legacydbtest.TypeMovie, Path: "/legacy/媒体/电影/Heat (1995)/Heat - 2160p.mkv"},
			{ID: lgMissing, Type: legacydbtest.TypeMovie, Path: "/legacy/媒体/电影/Gone/gone.mkv"},
			{ID: lgOutside, Type: legacydbtest.TypeVideo, Path: "/legacy/elsewhere/clip.mp4"},
			{ID: lgSeries, Type: legacydbtest.TypeSeries, Path: "/legacy/shows/Show"},
			{ID: lgSeason, Type: legacydbtest.TypeSeason, Path: "/legacy/shows/Show/Season 1"},
			{ID: lgEpisode, Type: legacydbtest.TypeEpisode, Path: "/legacy/shows/Show/Season 1/Show S01E01.mkv"},
			{ID: lgVirtual, Type: legacydbtest.TypeEpisode, Virtual: true},
			{ID: lgExtra, Type: legacydbtest.TypeVideo, Path: "/legacy/媒体/电影/Heat (1995)/extras/making.mkv", Extra: true},
			{ID: lgAudio, Type: legacydbtest.TypeAudio, Path: "/legacy/music/song.flac"},
			{ID: lgBook, Type: legacydbtest.TypeBook, Path: "/legacy/books/book.epub"},
			{ID: lgChannel, Type: legacydbtest.TypeLiveTvChannel},
			{ID: lgTrailer, Type: legacydbtest.TypeTrailer, Path: "/legacy/trailers/t.mkv"},
			{ID: lgFolder, Type: legacydbtest.TypeFolder, Path: "/legacy/媒体/电影"},
		},
		UserData: []legacydbtest.UserData{
			{UserID: lgAlice, ItemID: lgMovie1, Position: 12_000_000_000, PlayCount: 1, LastPlayed: "2025-03-01 20:15:00.1234567", Favorite: true},
			// Two rows of one user and item (CustomDataKey): the later one wins.
			{UserID: lgAlice, ItemID: lgMovie2, Key: "old", Position: 5, LastPlayed: "2024-01-01 00:00:00"},
			{UserID: lgAlice, ItemID: lgMovie2, Key: "new", Played: true, PlayCount: 3, LastPlayed: "2025-02-02 02:02:02"},
			// The other version of movie 2 becomes the same Jelee item.
			{UserID: lgAlice, ItemID: lgMovie2b, Position: 7, LastPlayed: "2023-01-01 00:00:00"},
			{UserID: lgBob, ItemID: lgEpisode, Played: true, PlayCount: 1},
			{UserID: lgBob, ItemID: lgMissing, Position: 99, LastPlayed: "2025-01-01 00:00:00"},
			{UserID: lgBob, ItemID: lgOutside, Position: 99, LastPlayed: "2025-01-01 00:00:00"},
			{UserID: lgBob, ItemID: lgSeries, Played: true},
			{UserID: lgCarol, ItemID: lgMovie1, Position: 1, LastPlayed: "2020-01-01 00:00:00"},
			{UserID: lgUnicode, ItemID: lgAudio, Played: true},
			{UserID: lgUnicode, ItemID: lgMovie2, Favorite: true},
			{UserID: lgUnicode, ItemID: lgEpisode},
			{UserID: lgUnicode, ItemID: lgPlaceItem, Played: true},
			{UserID: lgUnicode, ItemID: lgVanished, Played: true},
			{UserID: lgGone, ItemID: lgMovie1, Played: true},
		},
	}
}

func newLegacyScenario(t *testing.T, spec legacydbtest.Spec) legacyScenario {
	t.Helper()
	ctx, s, _ := accountTestStoreWithTimeout(t, 5*time.Minute)
	dir := t.TempDir()
	source := filepath.Join(dir, "上游 資料.db")
	if err := legacydbtest.Build(ctx, source, spec); err != nil {
		t.Fatal(err)
	}
	media := filepath.Join(dir, "媒體 target")
	return legacyScenario{ctx: ctx, s: s, source: source, media: media, rules: []domain.LegacyPathRule{{From: "/legacy", To: media}}}
}

func (sc legacyScenario) open(t *testing.T) *legacydb.Source {
	t.Helper()
	src, err := legacydb.Open(sc.ctx, sc.source, t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = src.Close() })
	return src
}

func (sc legacyScenario) run(t *testing.T, opts domain.LegacyImportOptions) (domain.LegacyImportReport, error) {
	t.Helper()
	if opts.PathMap == nil {
		opts.PathMap = sc.rules
	}
	if opts.FileExists == nil {
		opts.FileExists = func(p string) bool { return !strings.Contains(p, "/Gone/") }
	}
	return sc.s.LegacyImport(sc.ctx, sc.open(t), opts)
}

func (sc legacyScenario) count(t *testing.T, query string, args ...any) int64 {
	t.Helper()
	var n int64
	if err := sc.s.Pool.QueryRow(sc.ctx, query, args...).Scan(&n); err != nil {
		t.Fatalf("%s: %v", query, err)
	}
	return n
}

// scan registers the catalog a Jelee scan would build for the media the
// fixture names: the movie files, the episode and the series folder.
func (sc legacyScenario) scan(t *testing.T) map[string]string {
	t.Helper()
	root := func(path string) (string, string) {
		var id, library string
		if err := sc.s.Pool.QueryRow(sc.ctx, `SELECT id::text,library_id::text FROM library_roots WHERE path=$1`, path).Scan(&id, &library); err != nil {
			t.Fatalf("root %s: %v", path, err)
		}
		return id, library
	}
	moviesRoot, moviesLib := root(filepath.Join(sc.media, "媒体", "电影"))
	showsRoot, showsLib := root(filepath.Join(sc.media, "shows"))
	ids := map[string]string{}
	add := func(name, library, kind, title string) string {
		var id string
		if err := sc.s.Pool.QueryRow(sc.ctx, `INSERT INTO items(library_id,title,kind) VALUES($1::uuid,$2,$3) RETURNING id::text`, library, title, kind).Scan(&id); err != nil {
			t.Fatal(err)
		}
		ids[name] = id
		return id
	}
	source := func(item, library, root, rel string) {
		if _, err := sc.s.Pool.Exec(sc.ctx, `INSERT INTO media_sources(item_id,library_id,root_id,relative_path,content_type) VALUES($1::uuid,$2::uuid,$3::uuid,$4,'video/x-matroska')`,
			item, library, root, rel); err != nil {
			t.Fatal(err)
		}
	}
	m1 := add("movie1", moviesLib, "Movie", "千と千尋")
	source(m1, moviesLib, moviesRoot, "千と千尋 (2001)/千と千尋.mkv")
	m2 := add("movie2", moviesLib, "Movie", "Heat")
	source(m2, moviesLib, moviesRoot, "Heat (1995)/Heat - 1080p.mkv")
	source(m2, moviesLib, moviesRoot, "Heat (1995)/Heat - 2160p.mkv")
	series := add("series", showsLib, "Series", "Show")
	if _, err := sc.s.Pool.Exec(sc.ctx, `INSERT INTO item_directory_sources(item_id,library_id,kind,root_id,relative_path) VALUES($1::uuid,$2::uuid,'Series',$3::uuid,'Show')`, series, showsLib, showsRoot); err != nil {
		t.Fatal(err)
	}
	ep := add("episode", showsLib, "Episode", "Show S01E01")
	source(ep, showsLib, showsRoot, "Show/Season 1/Show S01E01.mkv")
	return ids
}

func sha256File(t *testing.T, path string) (string, time.Time) {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), info.ModTime()
}

func assertCategory(t *testing.T, r domain.LegacyImportReport, name string, want domain.LegacyCategoryReport) {
	t.Helper()
	got := r.Categories[name]
	if got == nil {
		t.Fatalf("%s missing", name)
	}
	type counts struct {
		Source, Inserted, Updated, Matched, Unchanged int64
		Skipped, Conflicts, Pending                   string
	}
	flat := func(c domain.LegacyCategoryReport) counts {
		return counts{c.Source, c.Inserted, c.Updated, c.Matched, c.Unchanged, fmt.Sprint(c.Skipped), fmt.Sprint(c.Conflicts), fmt.Sprint(c.Pending)}
	}
	if flat(*got) != flat(want) {
		t.Fatalf("%s:\n got  %+v\n want %+v", name, flat(*got), flat(want))
	}
}

// legacyTargetDigest summarizes the rows an import writes, to prove a
// repeated import changes nothing.
func (sc legacyScenario) targetDigest(t *testing.T) string {
	t.Helper()
	var digest string
	if err := sc.s.Pool.QueryRow(sc.ctx, `SELECT md5(concat_ws('|',
 (SELECT string_agg(concat_ws(',',id,name,is_admin,disabled,hidden,parental_rating_max,block_unrated,content_filtered,max_streams,max_kbps,password_hash,auth_version),';' ORDER BY id) FROM users),
 (SELECT string_agg(concat_ws(',',id,name),';' ORDER BY id) FROM libraries),
 (SELECT string_agg(concat_ws(',',library_id,path),';' ORDER BY path) FROM library_roots),
 (SELECT string_agg(concat_ws(',',user_id,library_id),';' ORDER BY user_id,library_id) FROM library_acl),
 (SELECT string_agg(concat_ws(',',user_id,tag),';' ORDER BY user_id,tag) FROM user_blocked_tags),
 (SELECT string_agg(concat_ws(',',user_id,item_id,resume_ticks,played,play_count,last_played_at,updated_at),';' ORDER BY user_id,item_id) FROM user_item_data),
 (SELECT string_agg(concat_ws(',',kind,source_key,target_id,target_user,created),';' ORDER BY kind,source_key) FROM legacy_import_map),
 (SELECT string_agg(concat_ws(',',source_key,reason,path),';' ORDER BY source_key) FROM legacy_import_pending)))`).Scan(&digest); err != nil {
		t.Fatal(err)
	}
	return digest
}

func TestLegacyImportFullThenScanThenIdempotentPostgres(t *testing.T) {
	sc := newLegacyScenario(t, legacyFixtureSpec())
	sumBefore, modBefore := sha256File(t, sc.source)
	// Carol already has a Jelee account: with --merge-users her progress goes
	// to it and the account itself is left alone.
	carol, err := sc.s.BootstrapAdmin(sc.ctx, accountInput("carol"))
	if err != nil {
		t.Fatal(err)
	}

	// First run: nothing is scanned yet, so every catalog item is pending.
	first, err := sc.run(t, domain.LegacyImportOptions{MergeUsers: true})
	if err != nil {
		t.Fatalf("first run: %v %+v", err, first)
	}
	if first.State != domain.LegacyStateCompleted || first.Resumed || !first.Verification.RowsBalanced || !first.Verification.TargetMatch || first.Source.SHA256 != sumBefore || !first.Source.Tested {
		t.Fatalf("first report %+v", first)
	}
	assertCategory(t, first, domain.LegacyCatUsers, domain.LegacyCategoryReport{Source: 4, Inserted: 3, Matched: 1})
	assertCategory(t, first, domain.LegacyCatPermissions, domain.LegacyCategoryReport{Source: 11, Inserted: 6,
		Skipped: map[string]int64{"download_removed": 1, "not_applicable": 2, "removed_domain": 1, "user_merged": 1}})
	assertCategory(t, first, domain.LegacyCatPreferences, domain.LegacyCategoryReport{Source: 4, Inserted: 3, Skipped: map[string]int64{"not_applicable": 1}})
	assertCategory(t, first, domain.LegacyCatLibraries, domain.LegacyCategoryReport{Source: 4, Inserted: 2, Skipped: map[string]int64{"removed_domain": 2}})
	assertCategory(t, first, domain.LegacyCatLibraryRoots, domain.LegacyCategoryReport{Source: 4, Inserted: 2,
		Skipped: map[string]int64{"duplicate_location": 1, "removed_domain": 1}})
	// Alice and the Unicode user see all folders (2 libraries each); bob
	// enabled the movies library and the skipped music library.
	assertCategory(t, first, domain.LegacyCatLibraryAccess, domain.LegacyCategoryReport{Source: 6, Inserted: 5, Skipped: map[string]int64{"library_not_imported": 1}})
	assertCategory(t, first, domain.LegacyCatItems, domain.LegacyCategoryReport{Source: 20,
		Skipped: map[string]int64{"extra": 1, "folder_unmatched": 2, "removed_domain": 3, "structural": 6, "unsupported_kind": 1, "virtual_item": 1},
		Pending: map[string]int64{"not_scanned": 4, "outside_roots": 1, "source_file_missing": 1}})
	assertCategory(t, first, domain.LegacyCatUserData, domain.LegacyCategoryReport{Source: 15,
		Skipped: map[string]int64{"empty": 1, "favorite_unsupported": 1, "item_detached": 1, "item_missing": 1, "item_not_mapped": 1, "merged_duplicate": 1, "removed_domain": 1, "user_missing": 1},
		Pending: map[string]int64{"item_pending": 7}})
	if first.PasswordResetRequired != 3 || len(first.Pending) != 6 || len(first.Conflicts) != 0 {
		t.Fatalf("first extras %+v", first)
	}
	for _, phase := range domain.LegacyImportPhases() {
		if first.Phases[phase] != "done" || first.Categories[legacyPhaseDigestCategory[phase][0]].Digest == "" {
			t.Fatalf("phase %s: %+v", phase, first.Phases)
		}
	}
	// Accounts: no password, upstream flags and limits, Unicode name kept.
	var admin, disabled, hidden, filtered bool
	var rating *int16
	var kbps *int64
	var streams *int32
	var hash *string
	if err = sc.s.Pool.QueryRow(sc.ctx, `SELECT is_admin,disabled,hidden,content_filtered,parental_rating_max,max_kbps,max_streams,password_hash FROM users WHERE id=$1`, lgBob).
		Scan(&admin, &disabled, &hidden, &filtered, &rating, &kbps, &streams, &hash); err != nil {
		t.Fatal(err)
	}
	if admin || disabled || hidden || !filtered || rating == nil || *rating != 13 || kbps == nil || *kbps != 8000 || streams == nil || *streams != 2 || hash != nil {
		t.Fatal("bob's account fields")
	}
	if sc.count(t, `SELECT count(*) FROM users WHERE id=$1 AND is_admin AND password_hash IS NULL`, lgAlice) != 1 ||
		sc.count(t, `SELECT count(*) FROM users WHERE id=$1 AND name='測試ユーザー' AND hidden AND disabled`, lgUnicode) != 1 ||
		sc.count(t, `SELECT count(*) FROM users WHERE id=$1 AND password_hash IS NOT NULL`, carol.ID) != 1 ||
		sc.count(t, `SELECT count(*) FROM user_blocked_tags WHERE user_id=$1 AND tag IN ('horror','gore')`, lgBob) != 2 ||
		sc.count(t, `SELECT count(*) FROM library_acl WHERE user_id=$1`, lgBob) != 1 ||
		sc.count(t, `SELECT count(*) FROM library_acl WHERE user_id=$1`, carol.ID) != 0 ||
		sc.count(t, `SELECT count(*) FROM libraries WHERE id=$1 AND name='電影 Movies'`, lgMovies) != 1 ||
		sc.count(t, `SELECT count(*) FROM setup_state WHERE completed_at IS NOT NULL`) != 1 ||
		sc.count(t, `SELECT count(*) FROM audit_logs WHERE event IN ('legacy.import_started','legacy.imported')`) != 2 {
		t.Fatal("first run target state")
	}

	// The libraries get scanned; the next run maps the pending items and
	// imports their progress.
	ids := sc.scan(t)
	second, err := sc.run(t, domain.LegacyImportOptions{MergeUsers: true})
	if err != nil || second.RunID == first.RunID || second.Resumed {
		t.Fatalf("second run: %v %+v", err, second)
	}
	assertCategory(t, second, domain.LegacyCatUsers, domain.LegacyCategoryReport{Source: 4, Unchanged: 4})
	assertCategory(t, second, domain.LegacyCatLibraries, domain.LegacyCategoryReport{Source: 4, Unchanged: 2, Skipped: map[string]int64{"removed_domain": 2}})
	assertCategory(t, second, domain.LegacyCatLibraryAccess, domain.LegacyCategoryReport{})
	assertCategory(t, second, domain.LegacyCatItems, domain.LegacyCategoryReport{Source: 20, Matched: 5,
		Skipped: map[string]int64{"extra": 1, "folder_unmatched": 1, "removed_domain": 3, "structural": 6, "unsupported_kind": 1, "virtual_item": 1},
		Pending: map[string]int64{"outside_roots": 1, "source_file_missing": 1}})
	assertCategory(t, second, domain.LegacyCatUserData, domain.LegacyCategoryReport{Source: 15, Inserted: 5,
		Skipped: map[string]int64{"empty": 1, "favorite_unsupported": 1, "item_detached": 1, "item_missing": 1, "merged_duplicate": 1, "merged_version": 1,
			"removed_domain": 1, "user_missing": 1},
		Pending: map[string]int64{"item_pending": 2}})
	if second.FavoritesDropped != 1 || !second.Verification.TargetMatch || second.Verification.TargetRows[domain.LegacyCatUserData] != 5 {
		t.Fatalf("second extras %+v", second)
	}
	var resume int64
	var played bool
	var count int32
	var last time.Time
	if err = sc.s.Pool.QueryRow(sc.ctx, `SELECT resume_ticks,played,play_count,last_played_at FROM user_item_data WHERE user_id=$1 AND item_id=$2`, lgAlice, ids["movie2"]).
		Scan(&resume, &played, &count, &last); err != nil || resume != 0 || !played || count != 3 || !last.Equal(time.Date(2025, 2, 2, 2, 2, 2, 0, time.UTC)) {
		t.Fatalf("merged progress: %v %d %t %d %v", err, resume, played, count, last)
	}
	if sc.count(t, `SELECT count(*) FROM user_item_data WHERE user_id=$1 AND item_id=$2 AND resume_ticks=12000000000 AND last_played_at='2025-03-01 20:15:00.123456+00'`, lgAlice, ids["movie1"]) != 1 ||
		sc.count(t, `SELECT count(*) FROM user_item_data WHERE user_id=$1 AND item_id=$2 AND played AND last_played_at IS NULL AND updated_at='epoch'`, lgBob, ids["episode"]) != 1 ||
		sc.count(t, `SELECT count(*) FROM user_item_data WHERE user_id=$1 AND item_id=$2 AND played`, lgBob, ids["series"]) != 1 ||
		sc.count(t, `SELECT count(*) FROM user_item_data WHERE user_id=$1 AND item_id=$2 AND resume_ticks=1`, carol.ID, ids["movie1"]) != 1 ||
		sc.count(t, `SELECT count(*) FROM legacy_import_pending`) != 2 {
		t.Fatal("second run target state")
	}

	// Newer progress in Jelee is never rewound by the old database.
	if _, err = sc.s.Pool.Exec(sc.ctx, `UPDATE user_item_data SET resume_ticks=42,updated_at=now() WHERE user_id=$1 AND item_id=$2`, lgAlice, ids["movie1"]); err != nil {
		t.Fatal(err)
	}
	before := sc.targetDigest(t)
	third, err := sc.run(t, domain.LegacyImportOptions{MergeUsers: true})
	if err != nil {
		t.Fatal(err)
	}
	assertCategory(t, third, domain.LegacyCatUserData, domain.LegacyCategoryReport{Source: 15, Unchanged: 5,
		Skipped: second.Categories[domain.LegacyCatUserData].Skipped, Pending: second.Categories[domain.LegacyCatUserData].Pending})
	if after := sc.targetDigest(t); after != before {
		t.Fatal("a repeated import changed the target")
	}
	if sc.count(t, `SELECT resume_ticks FROM user_item_data WHERE user_id=$1 AND item_id=$2`, lgAlice, ids["movie1"]) != 42 {
		t.Fatal("newer Jelee progress was rewound")
	}
	if sumAfter, modAfter := sha256File(t, sc.source); sumAfter != sumBefore || !modAfter.Equal(modBefore) {
		t.Fatal("the source database was modified")
	}
	if sc.count(t, `SELECT count(*) FROM legacy_import_runs WHERE state='completed' AND report->>'state'='completed'`) != 3 {
		t.Fatal("completed runs keep their report")
	}
	// The retained ledger blocks a downgrade that would forget it.
	f := jobFixture{ctx: sc.ctx, s: sc.s}
	refuseRetainedDowngrade(t, f, "legacy_import", "the legacy import ledger did not block the downgrade")
}

func TestLegacyImportResumesAfterFailedBatchPostgres(t *testing.T) {
	sc := newLegacyScenario(t, legacyFixtureSpec())
	sc.scanAfterLibraries(t)
	// The third items batch fails inside its transaction: that batch rolls
	// back, the two before it stay committed.
	failed := errors.New("injected")
	legacyImportBatchHook = func(phase string, batch int) error {
		if phase == domain.LegacyPhaseItems && batch == 3 {
			return failed
		}
		return nil
	}
	t.Cleanup(func() { legacyImportBatchHook = nil })
	report, err := sc.run(t, domain.LegacyImportOptions{MergeUsers: true, BatchSize: 3})
	if !errors.Is(err, failed) || report.State != domain.LegacyStateFailed || report.Error != "batch_failed" || report.Phases[domain.LegacyPhaseItems] != "partial" {
		t.Fatalf("failed run: %v %+v", err, report)
	}
	var batches int
	var cursor, lastError string
	if err = sc.s.Pool.QueryRow(sc.ctx, `SELECT c.batches,c.cursor,r.last_error FROM legacy_import_checkpoints c JOIN legacy_import_runs r ON r.id=c.run_id
 WHERE c.phase='items' AND r.state='running'`).Scan(&batches, &cursor, &lastError); err != nil || batches != 2 || cursor == "" || lastError != "batch_failed" {
		t.Fatalf("checkpoint after failure: %v batches=%d error=%q", err, batches, lastError)
	}
	// 6 of the 20 source items were read in the two committed batches.
	if sc.count(t, `SELECT count(*) FROM legacy_import_map WHERE kind='item'`)+sc.count(t, `SELECT count(*) FROM legacy_import_pending`) > 6 {
		t.Fatal("the failed batch left rows behind")
	}
	legacyImportBatchHook = nil
	resumed, err := sc.run(t, domain.LegacyImportOptions{MergeUsers: true, BatchSize: 7})
	if err != nil || !resumed.Resumed || resumed.RunID != report.RunID || resumed.State != domain.LegacyStateCompleted || !resumed.Verification.RowsBalanced || !resumed.Verification.TargetMatch {
		t.Fatalf("resumed run: %v %+v", err, resumed)
	}
	// The resumed run ends exactly where an uninterrupted one would.
	assertCategory(t, resumed, domain.LegacyCatItems, domain.LegacyCategoryReport{Source: 20, Matched: 5,
		Skipped: map[string]int64{"extra": 1, "folder_unmatched": 1, "removed_domain": 3, "structural": 6, "unsupported_kind": 1, "virtual_item": 1},
		Pending: map[string]int64{"outside_roots": 1, "source_file_missing": 1}})
	assertCategory(t, resumed, domain.LegacyCatUsers, domain.LegacyCategoryReport{Source: 4, Inserted: 4})
	assertCategory(t, resumed, domain.LegacyCatUserData, domain.LegacyCategoryReport{Source: 15, Inserted: 5,
		Skipped: map[string]int64{"empty": 1, "favorite_unsupported": 1, "item_detached": 1, "item_missing": 1, "merged_duplicate": 1, "merged_version": 1,
			"removed_domain": 1, "user_missing": 1},
		Pending: map[string]int64{"item_pending": 2}})
	if sc.count(t, `SELECT count(*) FROM legacy_import_runs`) != 1 || sc.count(t, `SELECT count(*) FROM users`) != 4 {
		t.Fatal("resume duplicated a run or an account")
	}
}

// scanAfterLibraries lets the libraries phase create the roots, then
// registers the catalog before the items phase runs.
func (sc legacyScenario) scanAfterLibraries(t *testing.T) {
	t.Helper()
	report, err := sc.run(t, domain.LegacyImportOptions{MergeUsers: true, BatchSize: 3, MaxBatches: 3})
	if err != nil || report.State != domain.LegacyStatePaused || report.Phases[domain.LegacyPhaseLibraries] != "partial" && report.Phases[domain.LegacyPhaseLibraries] != "done" {
		t.Fatalf("paused run: %v %+v", err, report)
	}
	// Two batches of users, one of libraries: run once more to finish them.
	report, err = sc.run(t, domain.LegacyImportOptions{MergeUsers: true, BatchSize: 3, MaxBatches: 2})
	if err != nil || report.State != domain.LegacyStatePaused || !report.Resumed || report.Phases[domain.LegacyPhaseLibraries] != "done" {
		t.Fatalf("paused run 2: %v %+v", err, report)
	}
	sc.scan(t)
}

func TestLegacyImportPreflightConflictsPostgres(t *testing.T) {
	spec := legacyFixtureSpec()
	spec.Libraries = append(spec.Libraries,
		legacydbtest.Library{ID: "b2000000-0000-4000-8000-000000000005", Name: "Anime", CollectionType: "tvshows", Locations: []string{`D:\Anime`}},
		legacydbtest.Library{ID: "b2000000-0000-4000-8000-000000000006", Name: "Docs", CollectionType: "", Locations: []string{"/legacy/docs"}},
		legacydbtest.Library{ID: "b2000000-0000-4000-8000-000000000007", Name: "Shows", CollectionType: "tvshows", Locations: []string{"/legacy/shows2"}},
		legacydbtest.Library{ID: "b2000000-0000-4000-8000-000000000008", Name: "Broken", CollectionType: "movies", RawData: "{not json"})
	spec.Users = append(spec.Users, legacydbtest.User{ID: "a1000000-0000-4000-8000-000000000005", Name: strings.Repeat("長", 50)})
	sc := newLegacyScenario(t, spec)
	if _, err := sc.s.BootstrapAdmin(sc.ctx, accountInput("CAROL")); err != nil {
		t.Fatal(err)
	}
	if _, err := sc.s.RegisterLibrary(sc.ctx, "Docs", filepath.Join(sc.media, "other docs")); err != nil {
		t.Fatal(err)
	}
	if _, err := sc.s.Pool.Exec(sc.ctx, `UPDATE users SET deleted_at=now() WHERE name='CAROL'`); err != nil {
		t.Fatal(err)
	}
	digest := sc.targetDigest(t)
	audits := sc.count(t, `SELECT count(*) FROM audit_logs`)
	report, err := sc.run(t, domain.LegacyImportOptions{PreflightOnly: true, MergeUsers: true})
	if !errors.Is(err, domain.ErrLegacyImportConflict) || report.State != domain.LegacyStatePreflight || report.RunID != "" {
		t.Fatalf("preflight: %v %+v", err, report)
	}
	want := map[string]map[string]int64{
		domain.LegacyCatUsers:        {"name_taken_deleted": 1, "name_invalid": 1},
		domain.LegacyCatLibraries:    {"root_path_unmapped": 1, "name_taken": 1, "name_duplicate": 1},
		domain.LegacyCatLibraryRoots: {"root_path_unmapped": 1},
	}
	for category, reasons := range want {
		if fmt.Sprint(report.Categories[category].Conflicts) != fmt.Sprint(reasons) {
			t.Fatalf("%s conflicts %v", category, report.Categories[category].Conflicts)
		}
	}
	if len(report.Conflicts) != 6 {
		t.Fatalf("conflict samples %+v", report.Conflicts)
	}
	// Without --skip-conflicts the import refuses and writes nothing.
	refused, err := sc.run(t, domain.LegacyImportOptions{MergeUsers: true})
	if !errors.Is(err, domain.ErrLegacyImportConflict) || refused.State != domain.LegacyStateRefused || sc.targetDigest(t) != digest ||
		sc.count(t, `SELECT count(*) FROM legacy_import_runs`) != 0 || sc.count(t, `SELECT count(*) FROM audit_logs`) != audits {
		t.Fatalf("refused run wrote: %v %+v", err, refused)
	}
	// With it the conflicting rows are skipped and counted.
	done, err := sc.run(t, domain.LegacyImportOptions{MergeUsers: true, SkipConflicts: true})
	if err != nil || done.State != domain.LegacyStateCompleted || !done.Verification.RowsBalanced {
		t.Fatalf("skip conflicts: %v %+v", err, done)
	}
	if fmt.Sprint(done.Categories[domain.LegacyCatUsers].Conflicts) != fmt.Sprint(want[domain.LegacyCatUsers]) ||
		sc.count(t, `SELECT count(*) FROM libraries WHERE name='Anime'`) != 0 || sc.count(t, `SELECT count(*) FROM users WHERE name='Carol'`) != 0 {
		t.Fatalf("skipped conflicts were imported: %+v", done.Categories)
	}
}

func TestLegacyImportRunGuardsPostgres(t *testing.T) {
	sc := newLegacyScenario(t, legacyFixtureSpec())
	paused, err := sc.run(t, domain.LegacyImportOptions{BatchSize: 2, MaxBatches: 1})
	if err != nil || paused.State != domain.LegacyStatePaused || paused.Batches != 1 {
		t.Fatalf("paused: %v %+v", err, paused)
	}
	// Other options while a run is unfinished: refused until --restart.
	other := []domain.LegacyPathRule{{From: "/legacy", To: filepath.Join(sc.media, "x")}}
	if _, err = sc.run(t, domain.LegacyImportOptions{PathMap: other}); !errors.Is(err, domain.ErrLegacyImportRunMismatch) {
		t.Fatalf("mismatch: %v", err)
	}
	restarted, err := sc.run(t, domain.LegacyImportOptions{PathMap: other, Restart: true})
	if err != nil || restarted.RunID == paused.RunID || restarted.State != domain.LegacyStateCompleted {
		t.Fatalf("restart: %v %+v", err, restarted)
	}
	if sc.count(t, `SELECT count(*) FROM legacy_import_runs WHERE id=$1 AND state='abandoned' AND finished_at IS NOT NULL`, paused.RunID) != 1 {
		t.Fatal("the replaced run was not abandoned")
	}
	// The accounts created before the restart are recognized, not duplicated.
	if restarted.Categories[domain.LegacyCatUsers].Unchanged != 2 || sc.count(t, `SELECT count(*) FROM users`) != 4 {
		t.Fatalf("restart duplicated accounts: %+v", restarted.Categories[domain.LegacyCatUsers])
	}
	// One import at a time.
	conn, err := sc.s.Pool.Acquire(sc.ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Release()
	if _, err = conn.Exec(sc.ctx, `SELECT pg_advisory_lock(hashtext(current_schema()),$1)`, legacyImportLock); err != nil {
		t.Fatal(err)
	}
	if _, err = sc.run(t, domain.LegacyImportOptions{}); !errors.Is(err, domain.ErrLegacyImportBusy) {
		t.Fatalf("busy: %v", err)
	}
	if _, err = conn.Exec(sc.ctx, `SELECT pg_advisory_unlock(hashtext(current_schema()),$1)`, legacyImportLock); err != nil {
		t.Fatal(err)
	}
	// Invalid options and a schema the binary does not know.
	if _, err = sc.run(t, domain.LegacyImportOptions{BatchSize: domain.LegacyImportMaxBatch + 1}); !errors.Is(err, domain.ErrInvalid) {
		t.Fatalf("batch size: %v", err)
	}
	if _, err = sc.s.Pool.Exec(sc.ctx, `UPDATE schema_migrations SET version=version+1`); err != nil {
		t.Fatal(err)
	}
	if _, err = sc.run(t, domain.LegacyImportOptions{}); !errors.Is(err, domain.ErrLegacyImportSchema) {
		t.Fatalf("schema: %v", err)
	}
	if _, err = sc.s.Pool.Exec(sc.ctx, `UPDATE schema_migrations SET version=version-1`); err != nil {
		t.Fatal(err)
	}
	// Deleting every run and ledger row makes the downgrade possible again.
	if _, err = sc.s.Pool.Exec(sc.ctx, `DELETE FROM legacy_import_map; DELETE FROM legacy_import_pending; DELETE FROM legacy_import_runs`); err != nil {
		t.Fatal(err)
	}
	f := jobFixture{ctx: sc.ctx, s: sc.s}
	version := downgradeAboveMigration(t, f, "legacy_import")
	dsn := sc.s.Pool.Config().ConnString()
	if v, dirty, err := Migrate(sc.ctx, dsn, "down"); err != nil || dirty || v != version-1 {
		t.Fatalf("down: %d %t %v", v, dirty, err)
	}
	if sc.count(t, `SELECT count(*) FROM information_schema.tables WHERE table_schema=current_schema() AND table_name LIKE 'legacy_import%'`) != 0 {
		t.Fatal("down left legacy import tables")
	}
	if v, dirty, err := Migrate(sc.ctx, dsn, "up"); err != nil || dirty || v != SchemaVersion {
		t.Fatalf("up: %d %t %v", v, dirty, err)
	}
}

// TestLegacyImportScale50000Postgres imports 50 000 items and 50 000 user
// data rows and checks that the Go heap stays bounded by the batch size.
func TestLegacyImportScale50000Postgres(t *testing.T) {
	const n = 50000
	spec := legacydbtest.Spec{
		Users:     []legacydbtest.User{{ID: lgAlice, Name: "scale", Permissions: map[int]bool{16: true}}},
		Libraries: []legacydbtest.Library{{ID: lgMovies, Name: "Movies", CollectionType: "movies", Locations: []string{"/legacy/movies"}}},
		MoreItems: func(add func(legacydbtest.Item) error) error {
			for i := range n {
				if err := add(legacydbtest.Item{ID: fmt.Sprintf("d4000000-0000-4000-8000-%012d", i), Type: legacydbtest.TypeMovie, Path: fmt.Sprintf("/legacy/movies/電影 %05d/movie.mkv", i)}); err != nil {
					return err
				}
			}
			return nil
		},
		MoreData: func(add func(legacydbtest.UserData) error) error {
			for i := range n {
				if err := add(legacydbtest.UserData{UserID: lgAlice, ItemID: fmt.Sprintf("d4000000-0000-4000-8000-%012d", i), Position: int64(i + 1), LastPlayed: "2025-01-01 00:00:00"}); err != nil {
					return err
				}
			}
			return nil
		},
	}
	sc := newLegacyScenario(t, spec)
	// Create the library through a paused import, then register the catalog.
	if report, err := sc.run(t, domain.LegacyImportOptions{MaxBatches: 2}); err != nil || report.Phases[domain.LegacyPhaseLibraries] == "pending" {
		t.Fatalf("libraries: %v %+v", err, report.Phases)
	}
	if _, err := sc.s.Pool.Exec(sc.ctx, `WITH r AS (SELECT id,library_id FROM library_roots),
 i AS (INSERT INTO items(library_id,title,kind) SELECT r.library_id,'movie '||g,'Movie' FROM r,generate_series(0,$1-1) g RETURNING id,title,library_id)
 INSERT INTO media_sources(item_id,library_id,root_id,relative_path,content_type)
 SELECT i.id,i.library_id,r.id,'電影 '||lpad(substr(i.title,7),5,'0')||'/movie.mkv','video/x-matroska' FROM i JOIN r ON r.library_id=i.library_id`, n); err != nil {
		t.Fatal(err)
	}
	runtime.GC()
	var base runtime.MemStats
	runtime.ReadMemStats(&base)
	var peak atomic.Uint64
	stop := make(chan struct{})
	var wg sync.WaitGroup
	wg.Go(func() {
		ticker := time.NewTicker(5 * time.Millisecond)
		defer ticker.Stop()
		for {
			select {
			case <-stop:
				return
			case <-ticker.C:
				var m runtime.MemStats
				runtime.ReadMemStats(&m)
				if m.HeapAlloc > peak.Load() {
					peak.Store(m.HeapAlloc)
				}
			}
		}
	})
	started := time.Now()
	report, err := sc.run(t, domain.LegacyImportOptions{})
	elapsed := time.Since(started)
	close(stop)
	wg.Wait()
	if err != nil || report.State != domain.LegacyStateCompleted || !report.Verification.RowsBalanced || !report.Verification.TargetMatch {
		t.Fatalf("scale run: %v %+v", err, report)
	}
	if c := report.Categories[domain.LegacyCatItems]; c.Matched != n {
		t.Fatalf("items %+v", c)
	}
	if c := report.Categories[domain.LegacyCatUserData]; c.Inserted != n {
		t.Fatalf("user data %+v", c)
	}
	growth := int64(peak.Load()) - int64(base.HeapAlloc)
	t.Logf("50000 items and user data rows: %s, heap peak growth %.1f MiB", elapsed.Round(time.Millisecond), float64(growth)/(1<<20))
	if growth > 64<<20 {
		t.Fatalf("heap grew %d bytes; the import must hold one batch at a time", growth)
	}
	if sc.count(t, `SELECT count(*) FROM user_item_data`) != n {
		t.Fatal("user data rows")
	}
}
