#!/usr/bin/env node
// Generates web/src/api/schema.d.ts from the committed api/openapi.json.
// With --check the file is regenerated in memory and compared, so CI fails
// whenever the server contract changed without regenerating the client types.
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const specURL = new URL("../../api/openapi.json", import.meta.url);
const outputURL = new URL("../src/api/schema.d.ts", import.meta.url);
const header =
  "// Code generated by web/scripts/api-types.mjs from api/openapi.json. DO NOT EDIT.\n" +
  "// Regenerate with `npm run api:generate --workspace @jelee/web`.\n\n";

export async function render() {
  const spec = JSON.parse(await readFile(specURL, "utf8"));
  const ast = await openapiTS(spec, {
    // Optional response fields stay optional; additionalProperties:false is
    // already the server contract, so no index signatures are emitted.
    exportType: true,
    alphabetize: true,
  });
  return header + astToString(ast);
}

async function main() {
  const check = process.argv.includes("--check");
  const generated = await render();
  if (!check) {
    await writeFile(outputURL, generated, "utf8");
    console.log("api types: wrote " + fileURLToPath(outputURL));
    return;
  }
  const committed = await readFile(outputURL, "utf8").catch(() => "");
  if (committed !== generated) {
    console.error(
      "api types: web/src/api/schema.d.ts is stale or missing; run `npm run api:generate --workspace @jelee/web`",
    );
    process.exit(1);
  }
  console.log("api types: web/src/api/schema.d.ts matches api/openapi.json");
}

await main();
