package images

import (
	"container/heap"
	"container/list"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"hash"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"sync/atomic"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/MoYuanCN/Jelee/internal/domain"
)

// Layout below StoreOptions.Root. Every name is generated by the store and is
// validated before it is read, accounted or removed:
//
//	originals/<sha256[:2]>/<sha256>          content-addressed original bytes
//	variants/<generation>/<source sha256>/<key>
//	                                          48-byte header plus derived bytes
//	tmp/put-<nonce>.partial                  private write staging, same filesystem
//	tmp/trash-<nonce>/                       a detached tree left by older versions
//
// <generation> is 16 hex digits. Only the highest generation is live; lower
// generations and pre-generation buckets (variants/<source sha256>/) are
// stale and are only ever removed, never indexed. ClearVariants creates the
// next generation instead of renaming the tree, so it does not depend on
// renaming a directory that holds open files, which Windows refuses.
//
// Anything else is foreign: it is counted but never read, moved or removed.
const (
	storeOriginalsDir = "originals"
	storeVariantsDir  = "variants"
	storeTempDir      = "tmp"
	storeHeaderMagic  = "JLVAR01\n"
	storeHeaderBytes  = int64(len(storeHeaderMagic) + 8 + sha256.Size)
	storeBatch        = 128
	// storeGenerationDigits names a variants generation directory; it cannot
	// collide with a 64-digit source bucket of the pre-generation layout.
	storeGenerationDigits = 16
	// Recency is persisted as file mtime so a restart keeps LRU order without
	// a separate journal. Coarse touches bound metadata writes on hot hits.
	storeTouchInterval = time.Minute
)

type storeClass uint8

const (
	storeOriginals storeClass = iota
	storeVariants
)

type StoreOptions struct {
	Root          string
	MediaRoots    []string
	OriginalBytes int64
	VariantBytes  int64
	// MaxEntries bounds the in-memory index of each class, independent of
	// bytes, so a library of tiny variants cannot grow the index unbounded.
	MaxEntries int
}

// Keep the public configuration and adapter bounds identical.
func validStoreOptions(o StoreOptions) bool {
	// No media roots is valid for a fresh installation; callers apply
	// CheckMediaRoot to every root they read from later.
	if !validStorePath(o.Root) || len(o.MediaRoots) > 1024 {
		return false
	}
	for _, root := range o.MediaRoots {
		if !validStorePath(root) {
			return false
		}
	}
	return o.OriginalBytes >= 64<<20 && o.OriginalBytes <= 4<<40 && o.VariantBytes >= 16<<20 && o.VariantBytes <= 1<<40 &&
		o.MaxEntries >= 1024 && o.MaxEntries <= 1<<21
}

func validStorePath(name string) bool {
	return len(name) <= 4096 && utf8.ValidString(name) && !strings.ContainsFunc(name, unicode.IsControl) && filepath.IsAbs(name)
}

// StoreStats contains aggregate counts only; digests and paths never become
// labels. Hits and misses per class provide the G42.4 hit-rate signal.
type StoreStats struct {
	OriginalEntries, VariantEntries           int
	OriginalBytes, VariantBytes               int64
	OriginalHits, OriginalMisses              uint64
	VariantHits, VariantMisses                uint64
	Evictions, Corrupt, Deduplicated, Cleared uint64
	RemoveErrors, Foreign                     uint64
}

type storeKey struct {
	class           storeClass
	source, variant [32]byte
}

type storeEntry struct {
	key  storeKey
	size int64
	// generation is the variants generation the file was written to; it is
	// fixed for the entry's lifetime and unused for originals.
	generation uint64
	touched    time.Time
}

func (e *storeEntry) file() string { return e.key.file(e.generation) }

type storeLRU struct {
	entries map[storeKey]*list.Element
	order   list.List
	bytes   int64
}

type storeKeyLock struct {
	held chan struct{}
	refs int
}

// Store is a persistent, content-addressed original and variant store. The
// index is authoritative for lookups; the filesystem is authoritative for
// content. All writes stage privately, fsync and rename atomically, so readers
// only open complete files. It only removes names it generates.
type Store struct {
	root       *os.Root
	path       string
	limits     [2]int64
	maxEntries int
	now        func() time.Time
	// A private seam lets tests fail durability before the atomic rename.
	syncFile func(*os.File) error
	// Private seams for every rename and remove, so tests can reproduce
	// platform refusals (Windows: open files, directories holding them).
	renameName func(oldName, newName string) error
	removeName func(name string) error
	// Writers hold tree shared from rename to index insertion. ClearVariants
	// holds it exclusively while it switches the live generation.
	tree sync.RWMutex
	// generation is the live variants generation. It changes only with tree
	// held exclusively; readers load it with tree held shared or for paths of
	// keys that are not indexed.
	generation atomic.Uint64
	// sweep serializes removal of stale generations.
	sweep   sync.Mutex
	mu      sync.Mutex
	classes [2]storeLRU
	locks   map[storeKey]*storeKeyLock
	closed  bool
	active  int
	done    chan struct{}

	hits, misses                              [2]atomic.Uint64
	evictions, corrupt, deduplicated, cleared atomic.Uint64
	removeErrors, foreign                     atomic.Uint64
}

// OpenStore validates the root like imageTempRoot, then rebuilds the bounded
// index from file metadata. Startup reads directories in fixed batches and
// keeps at most MaxEntries entries per class in memory.
func OpenStore(ctx context.Context, options StoreOptions) (*Store, error) {
	if ctx == nil || !validStoreOptions(options) {
		return nil, domain.ErrInvalid
	}
	return openStore(ctx, options)
}

func openStore(ctx context.Context, options StoreOptions) (*Store, error) {
	return openStoreWith(ctx, options, nil)
}

// openStoreWith lets tests replace the private seams before startup touches
// the tree, so startup cleanup runs under the same simulated refusals.
func openStoreWith(ctx context.Context, options StoreOptions, configure func(*Store)) (store *Store, resultErr error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if options.OriginalBytes < 1 || options.VariantBytes <= storeHeaderBytes || options.MaxEntries < 1 {
		return nil, domain.ErrInvalid
	}
	root, err := imageStoreRoot(options.Root, options.MediaRoots)
	if err != nil {
		return nil, err
	}
	s := &Store{root: root, path: filepath.Clean(options.Root), limits: [2]int64{options.OriginalBytes, options.VariantBytes}, maxEntries: options.MaxEntries,
		now: time.Now, syncFile: (*os.File).Sync, renameName: root.Rename, removeName: root.Remove,
		locks: make(map[storeKey]*storeKeyLock), done: make(chan struct{})}
	for index := range s.classes {
		s.classes[index].entries = make(map[storeKey]*list.Element)
	}
	if configure != nil {
		configure(s)
	}
	defer func() {
		if resultErr != nil {
			_ = root.Close()
			store = nil
		}
	}()
	for _, name := range []string{storeOriginalsDir, storeVariantsDir, storeTempDir} {
		if err := s.ensureDir(name); err != nil {
			return nil, err
		}
	}
	if err := s.openGeneration(ctx); err != nil {
		return nil, err
	}
	if err := s.cleanTemp(ctx); err != nil {
		return nil, err
	}
	if err := s.rebuild(ctx); err != nil {
		return nil, err
	}
	// Stale generations are never indexed; removing them is only reclaiming
	// space, and whatever cannot be removed now is retried later.
	if err := s.sweepVariants(ctx); err != nil {
		return nil, err
	}
	return s, nil
}

func imageStoreRoot(storeRoot string, mediaRoots []string) (*os.Root, error) {
	if !validStorePath(storeRoot) {
		return nil, domain.ErrImageUnavailable
	}
	clean := filepath.Clean(storeRoot)
	storeReal, err := filepath.EvalSymlinks(clean)
	// Reject aliases for the configured store directory, including ancestors.
	if err != nil || !imageSamePath(storeReal, clean) {
		return nil, domain.ErrImageUnavailable
	}
	for _, media := range mediaRoots {
		if checkStoreMediaRoot(storeReal, media) != nil {
			return nil, domain.ErrImageUnavailable
		}
	}
	before, err := os.Lstat(clean)
	if err != nil || before.Mode().Type() != os.ModeDir {
		return nil, domain.ErrImageUnavailable
	}
	root, err := os.OpenRoot(clean + string(os.PathSeparator) + ".")
	if err != nil {
		return nil, domain.ErrImageUnavailable
	}
	held, err := root.Open(".")
	if err != nil {
		_ = root.Close()
		return nil, domain.ErrImageUnavailable
	}
	heldInfo, statErr := held.Stat()
	privateErr := privateImageObject(held, true)
	closeErr := held.Close()
	if statErr != nil || privateErr != nil || closeErr != nil || !os.SameFile(before, heldInfo) {
		_ = root.Close()
		return nil, domain.ErrImageUnavailable
	}
	return root, nil
}

// checkStoreMediaRoot refuses either directory containing the other. An
// unavailable media root (an offline mount) is compared lexically instead.
func checkStoreMediaRoot(storeReal, media string) error {
	if !validStorePath(media) {
		return domain.ErrInvalid
	}
	candidates := []string{filepath.Clean(media)}
	if mediaReal, err := filepath.EvalSymlinks(media); err == nil {
		candidates = append(candidates, mediaReal)
	}
	for _, candidate := range candidates {
		if imagePathInside(candidate, storeReal) || imagePathInside(storeReal, candidate) {
			return domain.ErrImageUnavailable
		}
	}
	return nil
}

// CheckMediaRoot lets a later library change apply the startup overlap rule.
func (s *Store) CheckMediaRoot(media string) error {
	if s == nil {
		return domain.ErrInvalid
	}
	return checkStoreMediaRoot(s.path, media)
}

func (s *Store) enter() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return domain.ErrImageUnavailable
	}
	s.active++
	return nil
}

func (s *Store) leave() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.active--
	if s.closed && s.active == 0 {
		close(s.done)
	}
}

// Close waits for in-flight operations. Objects already returned keep their
// own file handles and remain readable after Close.
func (s *Store) Close(ctx context.Context) error {
	if s == nil || ctx == nil {
		return domain.ErrInvalid
	}
	s.mu.Lock()
	if !s.closed {
		s.closed = true
		if s.active == 0 {
			close(s.done)
		}
	}
	s.mu.Unlock()
	select {
	case <-s.done:
	case <-ctx.Done():
		return ctx.Err()
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	for index := range s.classes {
		s.classes[index] = storeLRU{entries: make(map[storeKey]*list.Element)}
	}
	if s.root != nil {
		err := s.root.Close()
		s.root = nil
		if err != nil {
			return domain.ErrImageUnavailable
		}
	}
	return nil
}

func (s *Store) Stats() StoreStats {
	if s == nil {
		return StoreStats{}
	}
	s.mu.Lock()
	result := StoreStats{OriginalEntries: s.classes[storeOriginals].order.Len(), VariantEntries: s.classes[storeVariants].order.Len(),
		OriginalBytes: s.classes[storeOriginals].bytes, VariantBytes: s.classes[storeVariants].bytes}
	s.mu.Unlock()
	result.OriginalHits, result.OriginalMisses = s.hits[storeOriginals].Load(), s.misses[storeOriginals].Load()
	result.VariantHits, result.VariantMisses = s.hits[storeVariants].Load(), s.misses[storeVariants].Load()
	result.Evictions, result.Corrupt, result.Deduplicated = s.evictions.Load(), s.corrupt.Load(), s.deduplicated.Load()
	result.Cleared, result.RemoveErrors, result.Foreign = s.cleared.Load(), s.removeErrors.Load(), s.foreign.Load()
	return result
}

// StoreVariantKey binds every output parameter. Source path, size and mtime
// are bound earlier: they select the original digest, which names the bucket.
func StoreVariantKey(pipeline, format string, width, height, quality int) [32]byte {
	digest := sha256.New()
	imageHashString(digest, "image-variant-v1")
	imageHashString(digest, pipeline)
	imageHashString(digest, format)
	var numbers [24]byte
	binary.BigEndian.PutUint64(numbers[:8], uint64(width))
	binary.BigEndian.PutUint64(numbers[8:16], uint64(height))
	binary.BigEndian.PutUint64(numbers[16:], uint64(quality))
	_, _ = digest.Write(numbers[:])
	var key [32]byte
	copy(key[:], digest.Sum(nil))
	return key
}

// path names the object; generation is ignored for originals.
func (k storeKey) path(generation uint64) (directory, name string) {
	if k.class == storeOriginals {
		name = hex.EncodeToString(k.source[:])
		return filepath.Join(storeOriginalsDir, name[:2]), name
	}
	return filepath.Join(storeGenerationDir(generation), hex.EncodeToString(k.source[:])), hex.EncodeToString(k.variant[:])
}

func (k storeKey) file(generation uint64) string {
	directory, name := k.path(generation)
	return filepath.Join(directory, name)
}

func storeGenerationName(generation uint64) string {
	var value [8]byte
	binary.BigEndian.PutUint64(value[:], generation)
	return hex.EncodeToString(value[:])
}

func storeGenerationDir(generation uint64) string {
	return filepath.Join(storeVariantsDir, storeGenerationName(generation))
}

// storeParseGeneration accepts only names storeGenerationName produces.
func storeParseGeneration(name string) (uint64, bool) {
	if !storeHexName(name, storeGenerationDigits) {
		return 0, false
	}
	var value [8]byte
	_, _ = hex.Decode(value[:], []byte(name))
	generation := binary.BigEndian.Uint64(value[:])
	return generation, generation > 0
}

// PutOriginal stores bytes under their SHA-256. A digest already present is
// deduplicated: the staged copy is discarded and the existing file is kept.
func (s *Store) PutOriginal(ctx context.Context, input io.Reader, limit int64) (digest [32]byte, size int64, err error) {
	if s == nil || ctx == nil || input == nil {
		return digest, 0, domain.ErrInvalid
	}
	if limit < 1 || limit > s.limits[storeOriginals] {
		return digest, 0, domain.ErrInvalid
	}
	if err := s.enter(); err != nil {
		return digest, 0, err
	}
	defer s.leave()
	staged, err := s.stage(ctx, input, limit, false)
	if err != nil {
		return digest, 0, err
	}
	defer staged.discard(s)
	key := storeKey{class: storeOriginals, source: staged.digest}
	if err := s.commit(ctx, key, staged); err != nil {
		return digest, 0, err
	}
	return staged.digest, staged.payload, nil
}

// PutVariant stores derived bytes for one source digest and variant key. The
// key lock is taken first, so concurrent producers of one key write once.
func (s *Store) PutVariant(ctx context.Context, source, variant [32]byte, input io.Reader, limit int64) (int64, error) {
	if s == nil || ctx == nil || input == nil {
		return 0, domain.ErrInvalid
	}
	if limit < 1 || limit > s.limits[storeVariants]-storeHeaderBytes {
		return 0, domain.ErrInvalid
	}
	if err := s.enter(); err != nil {
		return 0, err
	}
	defer s.leave()
	key := storeKey{class: storeVariants, source: source, variant: variant}
	unlock, err := s.lockKey(ctx, key)
	if err != nil {
		return 0, err
	}
	if size, ok := s.present(key); ok {
		unlock()
		s.deduplicated.Add(1)
		return size - storeHeaderBytes, nil
	}
	staged, err := s.stage(ctx, input, limit, true)
	if err != nil {
		unlock()
		return 0, err
	}
	defer staged.discard(s)
	victims, err := s.publish(key, staged)
	unlock()
	s.removeVictims(victims) //nolint:contextcheck // evicting already-unpublished entries must not be skipped when the request ends
	if err != nil {
		return 0, err
	}
	return staged.payload, nil
}

// HasOriginal reports whether the index holds an original. It does not open
// or validate the file; OpenOriginal does.
func (s *Store) HasOriginal(digest [32]byte) bool {
	if s == nil {
		return false
	}
	_, ok := s.present(storeKey{class: storeOriginals, source: digest})
	return ok
}

// VariantUsage reports the variant index size and its configured bounds, for
// eviction driven by the database index before the hard limits apply.
func (s *Store) VariantUsage() (bytes int64, entries int, limitBytes int64, maxEntries int) {
	if s == nil {
		return 0, 0, 0, 0
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	lru := &s.classes[storeVariants]
	return lru.bytes, lru.order.Len(), s.limits[storeVariants], s.maxEntries
}

// RemoveVariant drops one variant from the index and deletes its file. An
// unknown variant is not an error. Readers holding the object keep reading
// it; writers of the same key are excluded while the file is removed.
func (s *Store) RemoveVariant(ctx context.Context, source, variant [32]byte) error {
	if s == nil || ctx == nil {
		return domain.ErrInvalid
	}
	if err := s.enter(); err != nil {
		return err
	}
	defer s.leave()
	key := storeKey{class: storeVariants, source: source, variant: variant}
	unlock, err := s.lockKey(ctx, key)
	if err != nil {
		return err
	}
	defer unlock()
	// A key that is not indexed can only have a file in the live generation;
	// stale generations are removed as a whole.
	name := key.file(s.generation.Load())
	s.mu.Lock()
	if element, ok := s.classes[storeVariants].entries[key]; ok {
		name = s.dropLocked(element).file()
		s.evictions.Add(1)
	}
	s.mu.Unlock()
	// Removing a file another reader holds open succeeds on Unix and, through
	// os.Root's POSIX delete semantics, on NTFS; the reader keeps its bytes.
	if err := s.removeName(name); err != nil && !errors.Is(err, fs.ErrNotExist) {
		s.removeErrors.Add(1)
		return domain.ErrImageUnavailable
	}
	return nil
}

func (s *Store) present(key storeKey) (int64, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	element, ok := s.classes[key.class].entries[key]
	if !ok {
		return 0, false
	}
	return element.Value.(*storeEntry).size, true
}

func (s *Store) commit(ctx context.Context, key storeKey, staged *storeStaged) error {
	unlock, err := s.lockKey(ctx, key)
	if err != nil {
		return err
	}
	if _, ok := s.present(key); ok {
		unlock()
		s.deduplicated.Add(1)
		return nil
	}
	victims, err := s.publish(key, staged)
	unlock()
	s.removeVictims(victims) //nolint:contextcheck // evicting already-unpublished entries must not be skipped when the request ends
	return err
}

// publish must run with the key lock held. Rename and index insertion are one
// step with respect to ClearVariants.
func (s *Store) publish(key storeKey, staged *storeStaged) ([]*storeEntry, error) {
	s.tree.RLock()
	defer s.tree.RUnlock()
	generation := s.generation.Load()
	directory, _ := key.path(generation)
	if err := s.ensureDir(filepath.Dir(directory)); err != nil {
		return nil, err
	}
	if err := s.ensureDir(directory); err != nil {
		return nil, err
	}
	// The index and the restart recency hint start from one clock reading.
	now := s.now()
	_ = s.root.Chtimes(staged.name, now, now)
	if err := s.renameName(staged.name, key.file(generation)); err != nil {
		return nil, domain.ErrImageUnavailable
	}
	staged.name = ""
	// The object is already complete; a failed directory sync only weakens
	// crash durability of the name, which a later miss rebuilds.
	_ = s.syncDirectory(directory)
	s.mu.Lock()
	defer s.mu.Unlock()
	lru := &s.classes[key.class]
	if old, ok := lru.entries[key]; ok {
		lru.bytes -= old.Value.(*storeEntry).size
		lru.order.Remove(old)
	}
	lru.entries[key] = lru.order.PushFront(&storeEntry{key: key, size: staged.size, generation: generation, touched: now})
	lru.bytes += staged.size
	return s.evictLocked(key.class), nil
}

func (s *Store) evictLocked(class storeClass) []*storeEntry {
	lru := &s.classes[class]
	var victims []*storeEntry
	for lru.order.Len() > 0 && (lru.bytes > s.limits[class] || lru.order.Len() > s.maxEntries) {
		victim := s.dropLocked(lru.order.Back())
		victims = append(victims, victim)
		s.evictions.Add(1)
	}
	return victims
}

func (s *Store) dropLocked(element *list.Element) *storeEntry {
	entry := element.Value.(*storeEntry)
	lru := &s.classes[entry.key.class]
	delete(lru.entries, entry.key)
	lru.order.Remove(element)
	lru.bytes -= entry.size
	return entry
}

// removeVictims runs without any key lock held. A key published again after
// eviction is back in the index and its new file is kept.
func (s *Store) removeVictims(victims []*storeEntry) {
	for _, victim := range victims {
		key := victim.key
		unlock, err := s.lockKey(context.Background(), key)
		if err != nil {
			s.removeErrors.Add(1)
			continue
		}
		if _, ok := s.present(key); !ok {
			if err := s.removeName(victim.file()); err != nil && !errors.Is(err, fs.ErrNotExist) {
				// A later startup rebuild accounts for and evicts the file again.
				s.removeErrors.Add(1)
			}
		}
		unlock()
	}
}

func (s *Store) lockKey(ctx context.Context, key storeKey) (func(), error) {
	s.mu.Lock()
	lock := s.locks[key]
	if lock == nil {
		lock = &storeKeyLock{held: make(chan struct{}, 1)}
		s.locks[key] = lock
	}
	lock.refs++
	s.mu.Unlock()
	release := func() {
		s.mu.Lock()
		lock.refs--
		if lock.refs == 0 {
			delete(s.locks, key)
		}
		s.mu.Unlock()
	}
	select {
	case lock.held <- struct{}{}:
	case <-ctx.Done():
		release()
		return nil, ctx.Err()
	}
	var once sync.Once
	return func() { once.Do(func() { <-lock.held; release() }) }, nil
}

type storeStaged struct {
	name    string
	digest  [32]byte
	payload int64
	size    int64
}

func (staged *storeStaged) discard(s *Store) {
	if staged.name != "" {
		if err := s.removeName(staged.name); err != nil && !errors.Is(err, fs.ErrNotExist) {
			s.removeErrors.Add(1)
		}
		staged.name = ""
	}
}

// stage copies at most limit bytes into a new private file and fsyncs it.
// Any failure, including cancellation, removes the partial file.
func (s *Store) stage(ctx context.Context, input io.Reader, limit int64, header bool) (result *storeStaged, resultErr error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	var nonce [16]byte
	if _, err := rand.Read(nonce[:]); err != nil {
		return nil, domain.ErrImageUnavailable
	}
	staged := &storeStaged{name: filepath.Join(storeTempDir, "put-"+hex.EncodeToString(nonce[:])+".partial")}
	file, err := s.root.OpenFile(staged.name, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		return nil, domain.ErrImageUnavailable // An existing name is never owned here.
	}
	closed := false
	defer func() {
		if !closed {
			_ = file.Close()
		}
		if resultErr != nil {
			staged.discard(s)
		}
	}()
	if privateImageObject(file, false) != nil {
		return nil, domain.ErrImageUnavailable
	}
	offset := int64(0)
	if header {
		offset = storeHeaderBytes
		if _, err := file.Seek(offset, io.SeekStart); err != nil {
			return nil, domain.ErrImageUnavailable
		}
	}
	digest := sha256.New()
	count, err := storeCopy(ctx, io.MultiWriter(file, digest), input, limit)
	if err != nil {
		return nil, err
	}
	if count == 0 {
		return nil, domain.ErrInvalid
	}
	copy(staged.digest[:], digest.Sum(nil))
	staged.payload, staged.size = count, offset+count
	if header {
		if _, err := file.WriteAt(storeHeader(count, staged.digest), 0); err != nil {
			return nil, domain.ErrImageUnavailable
		}
	}
	if err := s.syncFile(file); err != nil {
		return nil, domain.ErrImageUnavailable
	}
	closed = true
	if err := file.Close(); err != nil {
		return nil, domain.ErrImageUnavailable
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	return staged, nil
}

func storeHeader(payload int64, digest [32]byte) []byte {
	value := make([]byte, storeHeaderBytes)
	copy(value, storeHeaderMagic)
	binary.BigEndian.PutUint64(value[len(storeHeaderMagic):], uint64(payload))
	copy(value[len(storeHeaderMagic)+8:], digest[:])
	return value
}

type storeContextReader struct {
	ctx    context.Context
	reader io.Reader
}

func (r storeContextReader) Read(data []byte) (int, error) {
	if err := r.ctx.Err(); err != nil {
		return 0, err
	}
	return r.reader.Read(data)
}

func storeCopy(ctx context.Context, out io.Writer, input io.Reader, limit int64) (int64, error) {
	buffer := imageCopyBuffers.Get().(*[32 << 10]byte)
	defer func() {
		clear(buffer[:])
		imageCopyBuffers.Put(buffer)
	}()
	n, err := io.CopyBuffer(out, io.LimitReader(storeContextReader{ctx, input}, limit+1), buffer[:])
	if ctx.Err() != nil {
		return n, ctx.Err()
	}
	if n > limit {
		return n, domain.ErrImageTooLarge
	}
	if err != nil {
		return n, domain.ErrImageUnavailable
	}
	return n, nil
}

// StoreObject is one complete stored object. It owns an open handle, so a
// concurrent eviction or ClearVariants cannot change what it reads on Unix.
type StoreObject struct {
	mu     sync.Mutex
	file   *os.File
	reader *io.SectionReader
	size   int64
}

func (*StoreObject) String() string   { return "stored image (redacted)" }
func (*StoreObject) GoString() string { return "stored image (redacted)" }

func (o *StoreObject) Size() int64 { return o.size }

func (o *StoreObject) Read(data []byte) (int, error) {
	o.mu.Lock()
	defer o.mu.Unlock()
	if o.reader == nil {
		return 0, io.ErrClosedPipe
	}
	return o.reader.Read(data)
}

func (o *StoreObject) Seek(offset int64, whence int) (int64, error) {
	o.mu.Lock()
	defer o.mu.Unlock()
	if o.reader == nil {
		return 0, io.ErrClosedPipe
	}
	return o.reader.Seek(offset, whence)
}

func (o *StoreObject) Close() error {
	o.mu.Lock()
	defer o.mu.Unlock()
	if o.file == nil {
		return nil
	}
	err := o.file.Close()
	o.file, o.reader = nil, nil
	if err != nil {
		return domain.ErrImageUnavailable
	}
	return nil
}

// OpenOriginal always checks size. verify also rehashes the content; callers
// use it when the bytes will be decoded or after an unclean shutdown.
func (s *Store) OpenOriginal(ctx context.Context, digest [32]byte, verify bool) (*StoreObject, error) {
	return s.open(ctx, storeKey{class: storeOriginals, source: digest}, verify)
}

// OpenVariant always checks the header length and payload digest; variants
// are bounded by the output limit, so a full hash is cheap.
func (s *Store) OpenVariant(ctx context.Context, source, variant [32]byte) (*StoreObject, error) {
	return s.open(ctx, storeKey{class: storeVariants, source: source, variant: variant}, true)
}

func (s *Store) open(ctx context.Context, key storeKey, verify bool) (object *StoreObject, resultErr error) {
	if s == nil || ctx == nil {
		return nil, domain.ErrInvalid
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if err := s.enter(); err != nil {
		return nil, err
	}
	defer s.leave()
	defer func() {
		if errors.Is(resultErr, domain.ErrNotFound) {
			s.misses[key.class].Add(1)
		}
	}()
	s.mu.Lock()
	element, ok := s.classes[key.class].entries[key]
	var expected int64
	var name string
	if ok {
		entry := element.Value.(*storeEntry)
		expected, name = entry.size, entry.file()
	}
	s.mu.Unlock()
	if !ok {
		return nil, domain.ErrNotFound
	}
	// os.Root opens with FILE_SHARE_DELETE on Windows, so holding this handle
	// never blocks eviction or clearing of the file.
	file, err := s.root.Open(name)
	if errors.Is(err, fs.ErrNotExist) {
		s.forget(element)
		return nil, domain.ErrNotFound
	}
	if err != nil {
		return nil, domain.ErrImageUnavailable
	}
	opened, statErr := file.Stat()
	offset, payload, checkErr := int64(0), expected, error(nil)
	if statErr != nil || privateImageObject(file, false) != nil || opened.Size() != expected {
		checkErr = domain.ErrImageUnavailable
	} else if key.class == storeVariants {
		offset, payload = storeHeaderBytes, expected-storeHeaderBytes
		checkErr = verifyStoreVariant(ctx, file, payload)
	} else if verify {
		checkErr = verifyStoreDigest(ctx, file, 0, payload, key.source)
	}
	if checkErr != nil {
		_ = file.Close()
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		s.discardCorrupt(element, opened) //nolint:contextcheck // removing a corrupt entry must not be skipped when the request ends
		return nil, domain.ErrNotFound
	}
	s.hits[key.class].Add(1)
	s.touch(element)
	return &StoreObject{file: file, reader: io.NewSectionReader(file, offset, payload), size: payload}, nil
}

func verifyStoreVariant(ctx context.Context, file *os.File, payload int64) error {
	if payload < 1 {
		return domain.ErrImageUnavailable
	}
	header := make([]byte, storeHeaderBytes)
	if _, err := file.ReadAt(header, 0); err != nil || string(header[:len(storeHeaderMagic)]) != storeHeaderMagic ||
		binary.BigEndian.Uint64(header[len(storeHeaderMagic):]) != uint64(payload) {
		return domain.ErrImageUnavailable
	}
	var digest [32]byte
	copy(digest[:], header[len(storeHeaderMagic)+8:])
	return verifyStoreDigest(ctx, file, storeHeaderBytes, payload, digest)
}

func verifyStoreDigest(ctx context.Context, file *os.File, offset, size int64, want [32]byte) error {
	digest := sha256.New()
	count, err := storeCopy(ctx, digest, io.NewSectionReader(file, offset, size), size)
	if err != nil {
		return err
	}
	if count != size || !storeDigestEqual(digest, want) {
		return domain.ErrImageUnavailable
	}
	return nil
}

func storeDigestEqual(digest hash.Hash, want [32]byte) bool {
	var got [32]byte
	copy(got[:], digest.Sum(nil))
	return got == want
}

// forget drops an index entry only if it is still the one that was looked up.
func (s *Store) forget(element *list.Element) {
	s.mu.Lock()
	defer s.mu.Unlock()
	entry := element.Value.(*storeEntry)
	if current, ok := s.classes[entry.key.class].entries[entry.key]; ok && current == element {
		s.dropLocked(element)
	}
}

// discardCorrupt removes only the exact file that failed validation. Writers
// of the key are excluded, and a replacement under the same name is kept.
func (s *Store) discardCorrupt(element *list.Element, opened os.FileInfo) {
	s.corrupt.Add(1)
	entry := element.Value.(*storeEntry)
	key, name := entry.key, entry.file()
	unlock, err := s.lockKey(context.Background(), key)
	if err != nil {
		return
	}
	defer unlock()
	s.forget(element)
	current, err := s.root.Lstat(name)
	if err != nil || opened == nil || !current.Mode().IsRegular() || !os.SameFile(current, opened) {
		return
	}
	if _, ok := s.present(key); ok {
		return
	}
	if err := s.removeName(name); err != nil && !errors.Is(err, fs.ErrNotExist) {
		s.removeErrors.Add(1)
	}
}

func (s *Store) touch(element *list.Element) {
	now := s.now()
	s.mu.Lock()
	entry := element.Value.(*storeEntry)
	current, ok := s.classes[entry.key.class].entries[entry.key]
	if !ok || current != element {
		s.mu.Unlock()
		return
	}
	s.classes[entry.key.class].order.MoveToFront(element)
	persist := now.Sub(entry.touched) >= storeTouchInterval
	if persist {
		entry.touched = now
	}
	s.mu.Unlock()
	if persist {
		// Best effort: mtime is only the restart recency hint.
		_ = s.root.Chtimes(entry.file(), now, now)
	}
}

// ClearVariants makes every stored variant stale in one step: it creates the
// next generation directory, then switches the live generation and empties
// the index together. Nothing is renamed, so a reader holding a variant open
// cannot make it fail on Windows. Store-generated files of stale generations
// are removed afterwards; originals are never touched. Readers that already
// hold an object keep reading it; later lookups miss and rebuild. A file that
// cannot be removed yet (a handle opened elsewhere without delete sharing, or
// a filesystem without POSIX delete semantics) stays in its stale generation,
// which is never indexed again and is retried by later clears and startups.
func (s *Store) ClearVariants(ctx context.Context) error {
	if s == nil || ctx == nil {
		return domain.ErrInvalid
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	if err := s.enter(); err != nil {
		return err
	}
	defer s.leave()
	s.tree.Lock()
	next := s.generation.Load() + 1
	if next == 0 {
		s.tree.Unlock()
		return domain.ErrImageUnavailable
	}
	if err := s.ensureDir(storeGenerationDir(next)); err != nil {
		s.tree.Unlock()
		return err
	}
	// The new directory is the durable commit point: a restart makes the
	// highest generation live, so cleared variants cannot be indexed again.
	if err := s.syncDirectory(storeVariantsDir); err != nil {
		s.tree.Unlock()
		return domain.ErrImageUnavailable
	}
	s.generation.Store(next)
	s.mu.Lock()
	s.classes[storeVariants] = storeLRU{entries: make(map[storeKey]*list.Element)}
	s.mu.Unlock()
	s.cleared.Add(1)
	s.tree.Unlock()
	return s.sweepVariants(ctx)
}

// openGeneration makes the highest generation live, creating the first one
// for a new store or one with the pre-generation layout. Top-level names that
// are neither generations nor pre-generation buckets are foreign.
func (s *Store) openGeneration(ctx context.Context) error {
	var live uint64
	err := s.storeEach(ctx, storeVariantsDir, func(entry fs.DirEntry) error {
		generation, ok := storeParseGeneration(entry.Name())
		switch {
		case entry.Type() == os.ModeDir && ok:
			live = max(live, generation)
		case entry.Type() == os.ModeDir && storeHexName(entry.Name(), 64):
			// A pre-generation bucket: stale, removed by sweepVariants.
		default:
			s.foreign.Add(1)
		}
		return nil
	})
	if err != nil {
		return err
	}
	if live == 0 {
		live = 1
		if err := s.ensureDir(storeGenerationDir(live)); err != nil {
			return err
		}
		_ = s.syncDirectory(storeVariantsDir) // Losing it loses only cache.
	}
	s.generation.Store(live)
	return s.ensureDir(storeGenerationDir(live))
}

// sweepVariants removes store-generated files of stale generations and of
// pre-generation buckets. Generations at or above the live one are skipped:
// a concurrent ClearVariants may have created the next one. Passes repeat
// while they remove a directory; what cannot be removed now is left for the
// next clear or startup and is never indexed meanwhile.
func (s *Store) sweepVariants(ctx context.Context) error {
	s.sweep.Lock()
	defer s.sweep.Unlock()
	live := s.generation.Load()
	for {
		removed := 0
		err := s.storeEach(ctx, storeVariantsDir, func(entry fs.DirEntry) error {
			if entry.Type() != os.ModeDir {
				return nil
			}
			name := filepath.Join(storeVariantsDir, entry.Name())
			if generation, ok := storeParseGeneration(entry.Name()); ok {
				if generation >= live {
					return nil
				}
				gone, err := s.removeTree(ctx, name)
				if gone {
					removed++
				}
				return err
			}
			if storeHexName(entry.Name(), 64) {
				count, err := s.removeBucket(ctx, name)
				removed += count
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
		if removed == 0 {
			return nil
		}
	}
}

func (s *Store) ensureDir(name string) error {
	if err := s.root.Mkdir(name, 0700); err != nil && !errors.Is(err, fs.ErrExist) {
		return domain.ErrImageUnavailable
	}
	before, err := s.root.Lstat(name)
	if err != nil || before.Mode().Type() != os.ModeDir {
		return domain.ErrImageUnavailable
	}
	held, err := s.root.Open(name)
	if err != nil {
		return domain.ErrImageUnavailable
	}
	info, statErr := held.Stat()
	privateErr := privateImageObject(held, true)
	closeErr := held.Close()
	if statErr != nil || privateErr != nil || closeErr != nil || !os.SameFile(before, info) {
		return domain.ErrImageUnavailable
	}
	return nil
}

func (s *Store) syncDirectory(name string) error {
	if runtime.GOOS == "windows" {
		return nil // Directory handles cannot be flushed there; rename is durable via NTFS logging.
	}
	directory, err := s.root.Open(name)
	if err != nil {
		return err
	}
	syncErr := directory.Sync()
	closeErr := directory.Close()
	return errors.Join(syncErr, closeErr)
}

func storeHexName(name string, length int) bool {
	if len(name) != length {
		return false
	}
	for index := 0; index < len(name); index++ {
		if c := name[index]; (c < '0' || c > '9') && (c < 'a' || c > 'f') {
			return false
		}
	}
	return true
}

func storeDecode(name string) (value [32]byte) {
	_, _ = hex.Decode(value[:], []byte(name))
	return value
}

// storeEach lists one directory in fixed batches. Entry types come from
// readdir without following symlinks.
func (s *Store) storeEach(ctx context.Context, name string, visit func(fs.DirEntry) error) error {
	directory, err := s.root.Open(name)
	if err != nil {
		return domain.ErrImageUnavailable
	}
	defer directory.Close()
	for {
		if err := ctx.Err(); err != nil {
			return err
		}
		batch, readErr := directory.ReadDir(storeBatch)
		for _, entry := range batch {
			if err := visit(entry); err != nil {
				return err
			}
		}
		if errors.Is(readErr, io.EOF) || readErr == nil && len(batch) == 0 {
			return nil
		}
		if readErr != nil {
			return domain.ErrImageUnavailable
		}
	}
}

// cleanTemp removes staging files and detached trees left by an interrupted
// process. Only names the store generates are removed.
func (s *Store) cleanTemp(ctx context.Context) error {
	var trash []string
	err := s.storeEach(ctx, storeTempDir, func(entry fs.DirEntry) error {
		name := entry.Name()
		switch {
		case entry.Type().IsRegular() && strings.HasPrefix(name, "put-") && strings.HasSuffix(name, ".partial") &&
			storeHexName(strings.TrimSuffix(strings.TrimPrefix(name, "put-"), ".partial"), 32):
			if err := s.removeName(filepath.Join(storeTempDir, name)); err != nil && !errors.Is(err, fs.ErrNotExist) {
				s.removeErrors.Add(1)
			}
		case entry.Type() == os.ModeDir && strings.HasPrefix(name, "trash-") && storeHexName(strings.TrimPrefix(name, "trash-"), 32):
			if len(trash) < storeBatch {
				trash = append(trash, filepath.Join(storeTempDir, name))
			}
		default:
			s.foreign.Add(1)
		}
		return nil
	})
	if err != nil {
		return err
	}
	for _, name := range trash {
		gone, err := s.removeTree(ctx, name)
		if err != nil {
			return err
		}
		if !gone {
			s.foreign.Add(1) // Foreign content stays for the operator to inspect.
		}
	}
	return nil
}

// removeTree deletes a detached or stale variants tree: <source>/<key> files
// whose names the store generates. Foreign entries keep their directory in
// place. Passes repeat while they delete something, so removal during
// readdir cannot skip entries; memory stays bounded by the batch size. It
// reports whether the tree itself is gone.
func (s *Store) removeTree(ctx context.Context, tree string) (bool, error) {
	for {
		removed := 0
		err := s.storeEach(ctx, tree, func(bucket fs.DirEntry) error {
			if bucket.Type() != os.ModeDir || !storeHexName(bucket.Name(), 64) {
				return nil
			}
			count, err := s.removeBucket(ctx, filepath.Join(tree, bucket.Name()))
			removed += count
			return err
		})
		if err != nil {
			return false, err
		}
		if removed == 0 {
			break
		}
	}
	err := s.removeName(tree)
	return err == nil || errors.Is(err, fs.ErrNotExist), nil
}

// removeBucket deletes the store-generated files of one <source> directory
// and then the directory if it became empty. It returns how many names it
// removed, counting the directory.
func (s *Store) removeBucket(ctx context.Context, directory string) (int, error) {
	removed := 0
	if err := s.storeEach(ctx, directory, func(entry fs.DirEntry) error {
		if entry.Type().IsRegular() && storeHexName(entry.Name(), 64) {
			if err := s.removeName(filepath.Join(directory, entry.Name())); err == nil {
				removed++
			} else if !errors.Is(err, fs.ErrNotExist) {
				s.removeErrors.Add(1)
			}
		}
		return nil
	}); err != nil {
		return removed, err
	}
	if s.removeName(directory) == nil {
		removed++
	}
	return removed, nil
}

// storeHeap keeps the newest MaxEntries objects seen during the rebuild; the
// root is the oldest, which is the first candidate to drop.
type storeHeap []*storeEntry

func (h storeHeap) Len() int           { return len(h) }
func (h storeHeap) Less(i, j int) bool { return h[i].touched.Before(h[j].touched) }
func (h storeHeap) Swap(i, j int)      { h[i], h[j] = h[j], h[i] }
func (h *storeHeap) Push(value any)    { *h = append(*h, value.(*storeEntry)) }
func (h *storeHeap) Pop() any {
	old := *h
	value := old[len(old)-1]
	old[len(old)-1] = nil
	*h = old[:len(old)-1]
	return value
}

// rebuild restores both indexes from names, sizes and mtimes. It never reads
// object content; validation happens lazily on open.
func (s *Store) rebuild(ctx context.Context) error {
	heaps := [2]storeHeap{}
	// Only the live generation is indexed. Stale generations and buckets of
	// the pre-generation layout hold cleared variants and are never read.
	live := s.generation.Load()
	add := func(key storeKey, info fs.FileInfo) {
		h := &heaps[key.class]
		entry := &storeEntry{key: key, size: info.Size(), generation: live, touched: info.ModTime()}
		if key.class == storeVariants && entry.size <= storeHeaderBytes || entry.size < 1 || entry.size > s.limits[key.class] {
			s.corrupt.Add(1)
			s.removeStored(entry)
			return
		}
		if h.Len() < s.maxEntries {
			heap.Push(h, entry)
			return
		}
		s.evictions.Add(1)
		if !(*h)[0].touched.Before(entry.touched) {
			s.removeStored(entry)
			return
		}
		s.removeStored((*h)[0])
		(*h)[0] = entry
		heap.Fix(h, 0)
	}
	err := s.storeEach(ctx, storeOriginalsDir, func(bucket fs.DirEntry) error {
		if bucket.Type() != os.ModeDir || !storeHexName(bucket.Name(), 2) {
			s.foreign.Add(1)
			return nil
		}
		directory := filepath.Join(storeOriginalsDir, bucket.Name())
		return s.storeEach(ctx, directory, func(entry fs.DirEntry) error {
			name := entry.Name()
			if !entry.Type().IsRegular() || !storeHexName(name, 64) || name[:2] != bucket.Name() {
				s.foreign.Add(1)
				return nil
			}
			info, err := entry.Info()
			if err != nil {
				return nil // Removed concurrently; nothing to account.
			}
			add(storeKey{class: storeOriginals, source: storeDecode(name)}, info)
			return nil
		})
	})
	if err != nil {
		return err
	}
	err = s.storeEach(ctx, storeGenerationDir(live), func(bucket fs.DirEntry) error {
		if bucket.Type() != os.ModeDir || !storeHexName(bucket.Name(), 64) {
			s.foreign.Add(1)
			return nil
		}
		directory := filepath.Join(storeGenerationDir(live), bucket.Name())
		source, objects := storeDecode(bucket.Name()), 0
		if err := s.storeEach(ctx, directory, func(entry fs.DirEntry) error {
			objects++
			if !entry.Type().IsRegular() || !storeHexName(entry.Name(), 64) {
				s.foreign.Add(1)
				return nil
			}
			info, err := entry.Info()
			if err != nil {
				return nil
			}
			add(storeKey{class: storeVariants, source: source, variant: storeDecode(entry.Name())}, info)
			return nil
		}); err != nil {
			return err
		}
		if objects == 0 {
			_ = s.removeName(directory) // Empty buckets come from earlier evictions.
		}
		return nil
	})
	if err != nil {
		return err
	}
	for class := range heaps {
		h := &heaps[class]
		lru := &s.classes[class]
		for h.Len() > 0 {
			entry := heap.Pop(h).(*storeEntry)
			lru.entries[entry.key] = lru.order.PushFront(entry)
			lru.bytes += entry.size
		}
		s.mu.Lock()
		victims := s.evictLocked(storeClass(class))
		s.mu.Unlock()
		for _, victim := range victims {
			s.removeStored(victim)
		}
	}
	return nil
}

// removeStored is used before the store is published to other goroutines.
func (s *Store) removeStored(entry *storeEntry) {
	if err := s.removeName(entry.file()); err != nil && !errors.Is(err, fs.ErrNotExist) {
		s.removeErrors.Add(1)
	}
}
